# Generated by Django 4.1.7 on 2023-03-02 03:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('boolean_field', models.BooleanField(null=True)),
                ('char_field', models.CharField(max_length=200, null=True)),
                ('datetime_field', models.DateTimeField(null=True)),
                ('text_field', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RelatedResource',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('boolean_field', models.BooleanField()),
                ('char_field', models.CharField(max_length=200)),
                ('datetime_field', models.DateTimeField()),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accord_site.resource')),
            ],
        ),
    ]
